/**
 * Writes apps/web/src/lib/og-icons.generated.ts: every pinned logo from
 * packages/ui/src/icons/manifest.json, downscaled to 96 px and inlined as a PNG data URI, so the
 * /api/og Worker draws logos without fetching its own static assets.
 *
 *   pnpm icons:og    (also run at the end of pnpm icons:sync)
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import sharp from "sharp";

const ROOT = resolve(import.meta.dirname, "..");
const MANIFEST_PATH = join(ROOT, "packages", "ui", "src", "icons", "manifest.json");
const PUBLIC_DIR = join(ROOT, "apps", "web", "public");
const OUT = join(ROOT, "apps", "web", "src", "lib", "og-icons.generated.ts");
const SIZE_PX = 96;

type Entry = { symbol: string; sha256: string; localPath: string };

export async function writeOgIcons(): Promise<void> {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as {
    icons: Record<string, Entry>;
  };
  const rows: string[] = [];
  let bytes = 0;
  for (const [mint, entry] of Object.entries(manifest.icons)) {
    const source = readFileSync(join(PUBLIC_DIR, entry.localPath));
    const sha256 = createHash("sha256").update(source).digest("hex");
    if (sha256 !== entry.sha256) {
      throw new Error(
        `${entry.symbol}: ${entry.localPath} doesn't match the manifest; run icons:sync`,
      );
    }
    const png = await sharp(source)
      .resize(SIZE_PX, SIZE_PX, { fit: "cover" })
      .png({ compressionLevel: 9, palette: true })
      .toBuffer();
    bytes += png.length;
    rows.push(
      `  ${JSON.stringify(mint)}: { symbol: ${JSON.stringify(entry.symbol)}, sourceSha256: ${JSON.stringify(sha256)}, dataUri: "data:image/png;base64,${png.toString("base64")}" },`,
    );
  }
  writeFileSync(
    OUT,
    `// Generated by scripts/og-icons.ts from packages/ui/src/icons/manifest.json. Do not edit.
// biome-ignore-all format: generated

export type OgIcon = { symbol: string; sourceSha256: string; dataUri: string };

/** ${SIZE_PX} px logos by mint, ${bytes} bytes of PNG before base64. */
export const OG_ICONS: Readonly<Record<string, OgIcon>> = {
${rows.join("\n")}
};
`,
  );
  console.log(`og icons: ${rows.length} logos, ${bytes} bytes, ${OUT}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href)
  await writeOgIcons();
