/**
 * Bakes the canonical fork bundle into the Worker: the manifest as committed, plus the report
 * `@paycheck-router/verify` produces by re-deriving every slice from the bundle's raw artifacts.
 * Run after the bundle changes: `pnpm --filter @paycheck-router/core build:proof`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { MANIFEST_FILE, RunManifest } from "@paycheck-router/shared";
import { verifyBundle } from "@paycheck-router/verify";

const BUNDLE_DIR = resolve(import.meta.dirname, "../../../evidence/stocklana-fork");
const OUT = resolve(import.meta.dirname, "../src/proof/generated/fork-bundle.ts");

const manifest = RunManifest.parse(
  JSON.parse(readFileSync(resolve(BUNDLE_DIR, MANIFEST_FILE), "utf8")),
);
const report = await verifyBundle(BUNDLE_DIR);

const source = `// Generated by apps/core/scripts/build-proof.ts from evidence/stocklana-fork. Do not edit.
import type { RunManifest } from "@paycheck-router/shared";
import type { BundleReport } from "../bundle-report.ts";

export const FORK_MANIFEST: RunManifest = ${JSON.stringify(manifest, null, 2)};

export const FORK_REPORT: BundleReport = ${JSON.stringify(report, null, 2)};
`;
writeFileSync(OUT, source);
console.log(
  `wrote ${OUT}: run ${manifest.runId}, ${report.slices.length} slices, bundle ${report.pass ? "PASS" : "FAIL"}`,
);
