/**
 * Bakes the canonical fork bundle into the Worker: the manifest as committed, plus the report
 * `@paycheck-router/verify` produces by re-deriving every slice from the bundle's raw artifacts.
 * Run after the bundle changes: `pnpm --filter @paycheck-router/core build:proof`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getPaycheckDecoder } from "@paycheck-router/sdk";
import { MANIFEST_FILE, RunManifest } from "@paycheck-router/shared";
import { verifyBundle } from "@paycheck-router/verify";
import { getBase64Encoder } from "@solana/kit";

const BUNDLE_DIR = resolve(import.meta.dirname, "../../../evidence/stocklana-fork");
const OUT = resolve(import.meta.dirname, "../src/proof/generated/fork-bundle.ts");

const manifest = RunManifest.parse(
  JSON.parse(readFileSync(resolve(BUNDLE_DIR, MANIFEST_FILE), "utf8")),
);
const report = await verifyBundle(BUNDLE_DIR);

/**
 * Times come from the Paycheck account read back after each execution (the program's clock),
 * not from getTransaction's blockTime, which Surfpool 1.5.0 reports divided by 1,000.
 */
const executedAt: Record<number, string> = {};
let recordedAt: string | null = null;
for (const leg of manifest.legs) {
  if (!leg.executed) continue;
  const raw = JSON.parse(readFileSync(resolve(BUNDLE_DIR, leg.executed.readback.path), "utf8")) as {
    result: { value: { data: [string, string] } };
  };
  const paycheck = getPaycheckDecoder().decode(
    Uint8Array.from(getBase64Encoder().encode(raw.result.value.data[0])),
  );
  recordedAt = new Date(Number(paycheck.recordedAt) * 1000).toISOString();
  const state = paycheck.legs[leg.index];
  if (state) executedAt[leg.index] = new Date(Number(state.executedAt) * 1000).toISOString();
}

const source = `// Generated by apps/core/scripts/build-proof.ts from evidence/stocklana-fork. Do not edit.
import type { RunManifest } from "@paycheck-router/shared";
import type { BundleReport } from "../bundle-report.ts";

export const FORK_MANIFEST: RunManifest = ${JSON.stringify(manifest, null, 2)};

export const FORK_REPORT: BundleReport = ${JSON.stringify(report, null, 2)};

/** From the Paycheck readbacks: when the paycheck was recorded and each slice executed. */
export const FORK_TIMES: { recordedAt: string | null; executedAt: Record<number, string> } = ${JSON.stringify({ recordedAt, executedAt }, null, 2)};
`;
writeFileSync(OUT, source);
console.log(
  `wrote ${OUT}: run ${manifest.runId}, ${report.slices.length} slices, bundle ${report.pass ? "PASS" : "FAIL"}`,
);
