"use client";

import { getAddressFromPublicKey, getBase58Decoder } from "@solana/kit";
import { registerWallet } from "@wallet-standard/wallet";
import { KeyPairAccount, KeyPairWallet } from "./keypair-wallet.ts";

/**
 * The hosted demo's wallet: an Ed25519 key pair generated by WebCrypto in this browser and kept
 * in this origin's IndexedDB. No server holds, sends or sees it. It only ever signs for the
 * hosted fork, where it is funded by the demo faucet; on mainnet it holds nothing.
 */
export const FORK_WALLET_NAME = "Fork demo wallet";

const ICON =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+PHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiBmaWxsPSIjMDBmZjk0Ii8+PHJlY3QgeD0iNSIgeT0iMTciIHdpZHRoPSI2IiBoZWlnaHQ9IjEwIiBmaWxsPSIjMGEwYTBmIi8+PHJlY3QgeD0iMTMiIHk9IjExIiB3aWR0aD0iNiIgaGVpZ2h0PSIxNiIgZmlsbD0iIzBhMGEwZiIvPjxyZWN0IHg9IjIxIiB5PSI1IiB3aWR0aD0iNiIgaGVpZ2h0PSIyMiIgZmlsbD0iIzBhMGEwZiIvPjwvc3ZnPg==" as const;

const DB_NAME = "pr-fork-wallet";
const STORE = "keys";
const KEY = "current";

type Stored = { keyPair: CryptoKeyPair; createdAt: string };

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, 1);
    request.onupgradeneeded = () => request.result.createObjectStore(STORE);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
}

async function withStore<T>(
  mode: IDBTransactionMode,
  run: (store: IDBObjectStore) => IDBRequest<T>,
): Promise<T> {
  const db = await openDb();
  try {
    return await new Promise<T>((resolve, reject) => {
      const request = run(db.transaction(STORE, mode).objectStore(STORE));
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
  } finally {
    db.close();
  }
}

/** The stored key pair, or a new one. Extractable only so the visitor can export it. */
async function loadOrCreate(): Promise<Stored> {
  const existing = await withStore<Stored | undefined>("readonly", (store) => store.get(KEY));
  if (existing) return existing;
  const keyPair = (await crypto.subtle.generateKey({ name: "Ed25519" }, true, [
    "sign",
    "verify",
  ])) as CryptoKeyPair;
  const created: Stored = { keyPair, createdAt: new Date().toISOString() };
  await withStore("readwrite", (store) => store.put(created, KEY));
  return created;
}

let registration: Promise<string> | null = null;

/** Registers the wallet once per page and resolves to its address. */
export function registerForkWallet(): Promise<string> {
  registration ??= (async () => {
    const { keyPair } = await loadOrCreate();
    const address = await getAddressFromPublicKey(keyPair.publicKey);
    const publicKey = new Uint8Array(await crypto.subtle.exportKey("raw", keyPair.publicKey));
    registerWallet(
      new KeyPairWallet(FORK_WALLET_NAME, ICON, keyPair, new KeyPairAccount(address, publicKey)),
    );
    return address;
  })();
  return registration;
}

/**
 * The secret key in the 64-byte Solana format (32-byte seed then public key), base58. For a
 * visitor who wants to inspect the fork wallet elsewhere; it holds nothing on mainnet.
 */
export async function exportForkWalletSecret(): Promise<string> {
  const { keyPair } = await loadOrCreate();
  const pkcs8 = new Uint8Array(await crypto.subtle.exportKey("pkcs8", keyPair.privateKey));
  const seed = pkcs8.slice(pkcs8.length - 32);
  const publicKey = new Uint8Array(await crypto.subtle.exportKey("raw", keyPair.publicKey));
  const secret = new Uint8Array(64);
  secret.set(seed, 0);
  secret.set(publicKey, 32);
  return getBase58Decoder().decode(secret);
}

/** Forgets the key pair; the next page load makes a new wallet. */
export async function resetForkWallet(): Promise<void> {
  await withStore("readwrite", (store) => store.delete(KEY));
  registration = null;
}
